package project1;

public class Javacategory {
	
	public static String[][] javaQuestions=new String[20][6];
	public static int javaQuestionPointer =0;
	
	public static void fillJavaArray() {
		
		javaQuestions[javaQuestionPointer][0]="\n Q1. What is the default value of char variable?\\n";
		javaQuestions[javaQuestionPointer][1]="1 - '\\\\u0000'\\n";
		javaQuestions[javaQuestionPointer][2]="2 - 0\\n";
		javaQuestions[javaQuestionPointer][3]="3 - null\\n";
		javaQuestions[javaQuestionPointer][4]="4 - not defined";
		javaQuestions[javaQuestionPointer][5]="1";
		javaQuestionPointer ++;
		
		javaQuestions[javaQuestionPointer][0]="\n Q2. What is JRE?\\n";
		javaQuestions[javaQuestionPointer][1]="1 - JRE is a java based GUI application.\\n";
		javaQuestions[javaQuestionPointer][2]="2 - JRE is an application development framework.\\n";
		javaQuestions[javaQuestionPointer][3]="3 - JRE is an implementation of the Java Virtual Machine which executes Java programs.\\n";
		javaQuestions[javaQuestionPointer][4]="4 - None of the above.";
		javaQuestions[javaQuestionPointer][5]="3 ";
		javaQuestionPointer ++;
		
		javaQuestions[javaQuestionPointer][0]="\n Q3. What is function overloading?\\n";
		javaQuestions[javaQuestionPointer][1]="1 - Methods with same name but different parameters.\\n";
		javaQuestions[javaQuestionPointer][2]="2 - Methods with same name but different return types.\\n";
		javaQuestions[javaQuestionPointer][3]="3 - Methods with same name, same parameter types but different parameter names.\\n";
		javaQuestions[javaQuestionPointer][4]="4 - None of the above.";
		javaQuestions[javaQuestionPointer][5]="1";
		javaQuestionPointer ++;
		
		javaQuestions[javaQuestionPointer][0]="\n Q4. Who is known as father of Java Programming Language?\\n";
		javaQuestions[javaQuestionPointer][1]="1. Blais Pascal\\n";
		javaQuestions[javaQuestionPointer][2]="2. M. P Java\\n";
		javaQuestions[javaQuestionPointer][3]="3. Charel Babbage\\n";
		javaQuestions[javaQuestionPointer][4]="4. James Gosling";
		javaQuestions[javaQuestionPointer][5]="4";
		javaQuestionPointer ++;
		
		javaQuestions[javaQuestionPointer][0]="\n Q5. In java control statements break, continue, return, try-catch-finally and assert belongs to?\\n";
		javaQuestions[javaQuestionPointer][1]="1. Selection statements\\n";
		javaQuestions[javaQuestionPointer][2]="2. Loop Statements\\n";
		javaQuestions[javaQuestionPointer][3]="3. Transfer statements\\n";
		javaQuestions[javaQuestionPointer][4]="4. Pause Statement";
		javaQuestions[javaQuestionPointer][5]="3";
		javaQuestionPointer ++;
		
		javaQuestions[javaQuestionPointer][0]="\n Q6. What is byte code in Java?\\n";
		javaQuestions[javaQuestionPointer][1]="1. Code generated by a Java compiler\\n";
		javaQuestions[javaQuestionPointer][2]="2. Code generated by a Java Virtual Machine\\n";
		javaQuestions[javaQuestionPointer][3]="3. Name of Java source code file\\n";
		javaQuestions[javaQuestionPointer][4]="4. Block of code written inside a class";
		javaQuestions[javaQuestionPointer][5]="1";
		javaQuestionPointer ++;
		
		javaQuestions[javaQuestionPointer][0]="\n Q7. Which of these is returned by operator '&' ?\\n";
		javaQuestions[javaQuestionPointer][1]="1. Integer\\n";
		javaQuestions[javaQuestionPointer][2]="2. Character\\n";
		javaQuestions[javaQuestionPointer][3]="3. Boolean\\n";
		javaQuestions[javaQuestionPointer][4]="4. Float";
		javaQuestions[javaQuestionPointer][5]="2";
		javaQuestionPointer ++;
		
		javaQuestions[javaQuestionPointer][0]="\n Q8. Data type long literals are appended by _____\\n";
		javaQuestions[javaQuestionPointer][1]="1. Uppercase L\\n";
		javaQuestions[javaQuestionPointer][2]="2. Lowercase L\\n";
		javaQuestions[javaQuestionPointer][3]="3. Long\\n";
		javaQuestions[javaQuestionPointer][4]="4. Both A and B";
		javaQuestions[javaQuestionPointer][5]="4";
		javaQuestionPointer ++;
		
		javaQuestions[javaQuestionPointer][0]="\n Q9. Java language was initially called as ________\\n";
		javaQuestions[javaQuestionPointer][1]="1. Sumatra\\n";
		javaQuestions[javaQuestionPointer][2]="2. J++\\n";
		javaQuestions[javaQuestionPointer][3]="3. Oak\\n";
		javaQuestions[javaQuestionPointer][4]="4. Pine";
		javaQuestions[javaQuestionPointer][5]="3";
		javaQuestionPointer ++;
		
		javaQuestions[javaQuestionPointer][0]="\n Q10. Which of these operators is used to allocate memory to array variable in Java?\\n";
		javaQuestions[javaQuestionPointer][1]="1. alloc\\n";
		javaQuestions[javaQuestionPointer][2]="2. malloc\\n";
		javaQuestions[javaQuestionPointer][3]="3. new malloc\\n";
		javaQuestions[javaQuestionPointer][4]="4. new";
		javaQuestions[javaQuestionPointer][5]="4";
		javaQuestionPointer ++;
		
		
	}

}